### ISSUE TITLE
Questions about the definition of IPC in validate.py

### ISSUE THREAD

**Issue by SunSwallow** [vimar-gu/DiM#1]
Hello, I'm very interested in your work about combining GAN and DC! But, I am very confused about the definition of IPC in the code **validate.py**. 
In line 201, there is a function called _validate(args, generator, testloader, criterion, aug_rand)_. It seems like a function which generates synthesized data and train a model on it to evaluate the model performance. However, it seems like in every batch, the synthesized data is regenerated because the noise _z_ is randomized in line 226. It's different from the traditional way in GradientMatching or MatchingTrainingTrajectory where the synthesized images is generated before evaluating and fixed during evaluating, which means that in every epoch, the images are the same. 
Is there anything I understand wrong about DiM? Looking forward to your kind explanation!

**Comment by vimar-gu** [comment]
Sorry for the late reply. 
For DiM the dataset is distilled into the generative models. Therefore, we use the same forward number when compared with DiI methods. It is a special characteristic for the DiM scheme, where much higher diversity is provided. 
Although it may seem unfair as the generative model is much larger than several images of CIFAR, when it comes to larger datasets like ImagaNet, the storage space will no more become a drawback for DiM.

**Comment by SunSwallow** [comment]
Thanks for the reply!
